version: '2'
services:
  element_0:
    image: 'output_hnode_40_kali:latest'
    stdin_open: true
    tty: true
    networks:
      network: {}
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 193.20.1.1/24
