version: '2'
services:
  website:
    image: 'dockersecplayground/linode_lamp:v2.0'
    stdin_open: true
    tty: true
    ports:
      - '8090:80'
    volumes:
      - './website:/var/www/'
networks: {}
