version: '2'
services:
  guacd:
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw
  postgres:
    image: postgres:15.2-alpine
    networks:
      guacnetwork_compose:
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'Cpassword'
      POSTGRES_USER: guacamole_user
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:Z
  guacamole:
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'Cpassword'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
      - guacd
    networks:
      guacnetwork_compose:
    ports:
      - 8080:8080
    restart: always
networks:
  guacnetwork_compose:
    driver: bridge

