version: '2'
services:
  router:
    image: 'dockersecplayground/alpine_router:v1.0'
    stdin_open: true
    tty: true
    networks:
      internal:
        ipv4_address: 175.59.2.2
      external:
        ipv4_address: 193.25.1.2
    cap_add:
      - ALL
  dvwa-web:
    image: 'ghcr.io/darkness4/dvwa-docker:latest'
    stdin_open: true
    tty: true
    ports:
      - '80:3000'
    networks:
      external:
        ipv4_address: 193.25.1.3
      internal:
        ipv4_address: 175.59.2.4
    environment:
      - MYSQL_HOST=175.59.2.3
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=localrootpassword
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
      - WAIT_HOSTS=database:3306
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=5
    depends_on:
      - dvwa-db
    volumes:
      - './config:/config'
  dvwa-db:
    image: 'mariadb:10.7'
    stdin_open: true
    tty: true
    ports:
      - '3306:3306'
    networks:
      internal:
        ipv4_address: 175.59.2.3
    environment:
      - MYSQL_HOST=175.59.2.3
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=localrootpassword
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
      - WAIT_HOSTS=database:3306
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=5
    volumes:
      - './database_data:/var/lib/mysql'
  md-db-admin:
    image: 'webpwnized/mutillidae:database_admin'
    stdin_open: true
    tty: true
    ports:
      - '81:81'
    networks:
      internal:
        ipv4_address: 175.59.2.6
    environment:
      - PMA_HOST=175.59.2.5
      - MYSQL_ROOT_PASSWORD=mutillidae
      - PMA_USER=root
      - PMA_PASSWORD=mutillidae
    depends_on:
      - database
  database:
    image: 'webpwnized/mutillidae:database'
    stdin_open: true
    tty: true
    networks:
      internal:
        ipv4_address: 175.59.2.5
    environment:
      - MYSQL_ROOT_PASSWORD=mutillidae
  directory_admin:
    image: 'webpwnized/mutillidae:ldap_admin'
    stdin_open: true
    tty: true
    ports:
      - '85:82'
    networks:
      external:
        ipv4_address: 193.25.1.6
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=193.25.1.5
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - directory
  directory:
    image: 'webpwnized/mutillidae:ldap'
    stdin_open: true
    tty: true
    ports:
      - '389:389'
    networks:
      external:
        ipv4_address: 193.25.1.5
    environment:
      - LDAP_ORGANISATION="Mutillidae Inc"
      - LDAP_DOMAIN="mutillidae.localhost"
      - LDAP_BASE_DN="dc=mutillidae,dc=localhost"
      - LDAP_ADMIN_PASSWORD="mutillidae"
      - LDAP_CONFIG_PASSWORD="mutillidae"
      - LDAP_TLS="false"
    volumes:
      - './ldap_data:/var/lib/ldap'
      - './ldap_config:/etc/ldap/slapd.d'
  mutillidae-web:
    image: 'webpwnized/mutillidae:www'
    stdin_open: true
    tty: true
    ports:
      - '8080:80'
      - '443:443'
      - '84:8888'
    networks:
      external:
        ipv4_address: 193.25.1.4
      internal:
        ipv4_address: 175.59.2.7
    depends_on:
      - database
      - directory
networks:
  external:
    ipam:
      config:
        - subnet: 193.25.1.1/24
  internal:
    ipam:
      config:
        - subnet: 175.59.2.1/24
