version: '2'
services:
  DSVW:
    image: 'm4n3dw0lf/dsvw:latest'
    stdin_open: true
    tty: true
    ports:
      - '8081:8081'
    networks:
      internal:
        ipv4_address: 172.26.1.2
  webgoat:
    image: 'mrmendes/webgoat-docker:latest'
    stdin_open: true
    tty: true
    ports:
      - '8082:8080'
    networks:
      internal:
        ipv4_address: 172.26.1.3
  javavulnlab:
    image: 'm4n3dw0lf/javavulnerablelab:latest'
    stdin_open: true
    tty: true
    ports:
      - '8083:8080'
    networks:
      internal:
        ipv4_address: 172.26.1.4
    links:
      - mysql
  mysql:
    image: 'mysql:5.5'
    stdin_open: true
    tty: true
    networks:
      internal:
        ipv4_address: 172.26.1.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
  drupal:
    image: 'vulhub/drupal:8.5.0'
    stdin_open: true
    tty: true
    ports:
      - '8080:80'
    networks:
      internal:
        ipv4_address: 172.26.1.5
  ecshop36:
    image: 'vulhub/ecshop:3.6.0'
    stdin_open: true
    tty: true
    ports:
      - '8084:80'
    networks:
      internal:
        ipv4_address: 172.26.1.7
    depends_on:
      - mysql
  grafana:
    image: 'vulhub/grafana:8.2.6'
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    networks:
      internal:
        ipv4_address: 172.26.1.8
  jenkins:
    image: 'vulhub/jenkins:2.441'
    stdin_open: true
    tty: true
    ports:
      - '5005:5005'
      - '8087:8080'
      - '50000:50000'
    networks:
      internal:
        ipv4_address: 172.26.1.9
    environment:
      - DEBUG=1
  log4j:
    image: 'vulhub/solr:8.11.0'
    stdin_open: true
    tty: true
    ports:
      - '5006:5005'
      - '8983:8983'
    networks:
      internal:
        ipv4_address: 172.26.1.10
networks:
  internal:
    ipam:
      config:
        - subnet: 172.26.1.1/24
